
/*
    Challenge 1.
    Write a SQL query that counts the number of films in each category in the Pagila database.
    - The query should return two columns: category and film_count
    - category should display the name of each category
    - film_count should show the total number of films in that category
    - Results should be grouped by category name
 */

SELECT c.name AS category, count(fc.film_id) AS film_count
FROM category c
LEFT JOIN film_category fc ON fc.category_id = c.category_id
GROUP BY c.name
ORDER BY film_count DESC;

 /*
    Challenge 2.
    Write a SQL query that finds the top 5 customers who have spent the most money in the Pagila database.
    - The query should return three columns: first_name, last_name, and total_spent
    - total_spent should show the sum of all payments made by that customer
    - Results should be ordered by total_spent in descending order
    - The query should limit results to only the top 5 highest-spending customers
 */

/*
// output : first_name, last_name, total_spent
// grain:  customer
// agg / verbs: group by, sum, order by desc, limit
// entities: customer, payment
// path between them: customer -> payment (customer_id)
// classify every filter: none
// order:
// did join mult rows?:
*/

SELECT c.first_name, c.last_name, SUM(p.amount) AS total_spent
FROM customer c
JOIN payment p ON c.customer_id = p.customer_id
GROUP BY c.first_name, c.last_name, c.customer_id
ORDER BY total_spent DESC
LIMIT 5;





/*
    Challenge 3.
    Write a SQL query that lists all film titles that have been rented in the past 10 years in the Pagila database.
    - The query should return one column: title
    - title should display the name of each film that has been rented
    - The time period for "recent" should be within the last 10 years from the current date
    - Results should only include films that have rental records in this time period
*/

/*
// output: title
// grain: one row per film
// agg / verbs: -
// entities: film, inventory, rental
// path between them: film.film_id = inventory.film_id, inventory.inventory_id = rental.inventory_id
// classify every filter: WHERE
// order: FROM film JOIN inventory JOIN rental → WHERE rental_date filter → SELECT DISTINCT title
// did join mult rows?: yes, multiplies. need DISTINCT
*/

SELECT DISTINCT f.title
FROM film f
JOIN inventory i ON i.film_id = f.film_id
JOIN rental r ON r.inventory_id = i.inventory_id
WHERE r.rental_date >= current_date - interval '10 years';

/*
    Challenge 4.
    Write a SQL query that lists all films that have never been rented in the Pagila database.
    - The query should return two columns: title and inventory_id
    - title should display the name of each film that has never been rented
    - inventory_id should show the inventory ID of the specific copy
*/


/*
// output columns: film.title inventory.inventory_id 
// grain (one row = ?): one row per unrented inventory copy
// verb → clause (SUM/COUNT/none): none
// entities (tables): film, inventory, rental
// join type (INNER / LEFT / anti-join) + why: left join, keep unmatched rows as null
// path (ON conditions): film.film_id = inventory.film_id, inventory.inventory_id = rental.inventory_id
// filter: WHERE (before group) or HAVING (only if an aggregate exists): WHERE
// assembled skeleton (FROM→WHERE→GROUP BY→HAVING→SELECT→ORDER BY→LIMIT):
// fan-out check: does any join multiply rows? how did you verify:
*/

SELECT f.title, i.inventory_id
FROM film f
JOIN inventory i ON i.film_id = f.film_id
LEFT JOIN rental r ON r.inventory_id = i.inventory_id
WHERE  r.rental_id IS NULL;



/*
    Challenge 5.
    Write a SQL query that lists all films that were rented more times than the average rental count per film in the Pagila database.
    - The query should return two columns: title and rental_count
    - title should display the name of each film
    - rental_count should show the total number of times the film was rented
*/



-- your query here

/*
    Challenge 6.
    Write a SQL query that calculates rental activity for each customer.
    - The query should return the customer's first_name and last_name
    - It should also return their first rental date as first_rental
    - Their most recent rental date should be shown as last_rental
    - The difference in days between the first and last rentals should be shown as rental_span_days
    - Results should be grouped by customer and ordered by rental_span_days in descending order
*/

-- your query here

/*
    Challenge 7.
    Find all customers who have not rented movies from every available genre.
    - The result should include the customer's first_name and last_name
    - Only include customers who are missing at least one genre in their rental history
*/


-- your query here


/*
    Challenge 8.
    Create a materialized view that summarizes total rental revenue per film category.

    First, write a SQL query that returns the category name and the total revenue generated by rentals in that category.

    Use the following tables: payment, rental, inventory, film, film_category, and category.

    - Group the results by category name and order them by total revenue (descending).
    - Then, turn your query into a materialized view named revenue_by_category.
    - Query the materialized view to return:
    - All categories and their total revenue.
    - The top 3 categories by revenue.
    - Finally, refresh the materialized view manually using SQL.

    Once you finish the exercise, please answer the following questions: 
    
    When would you prefer a materialized view over a regular view? 
    How often should it be refreshed?
*/

-- your work here




